//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MajorTeachPlan
    {
        public int id { get; set; }
        public int y_year { get; set; }
        public int y_majorId { get; set; }
        public int y_teachPlanId { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string y_name { get; set; }
        public string y_code { get; set; }
        public Nullable<int> y_stuYear { get; set; }
        public string stuTypeName { get; set; }
        public string y_stuTypeCode { get; set; }
        public string eduTypeName { get; set; }
        public string y_eduTypeCode { get; set; }
        public string majorLibraryName { get; set; }
        public string majorLibraryCode { get; set; }
        public string y_teaPlanName { get; set; }
        public int y_teaPlanType { get; set; }
        public Nullable<int> y_term { get; set; }
    }
}
