//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Strange
    {
        public int id { get; set; }
        public int y_strangeType { get; set; }
        public System.DateTime y_applyTime { get; set; }
        public string y_applyReason { get; set; }
        public string y_approvalReason { get; set; }
        public Nullable<System.DateTime> y_approvalTime { get; set; }
        public int y_approvalStatus { get; set; }
        public Nullable<int> y_approvalAdmin { get; set; }
        public int y_applyAdmin { get; set; }
        public string y_contentA { get; set; }
        public string y_contentB { get; set; }
        public string y_contentC { get; set; }
        public string y_contentD { get; set; }
        public string y_contentE { get; set; }
        public int y_isExecutive { get; set; }
        public Nullable<System.DateTime> y_ExecutiveTime { get; set; }
        public int y_stuId { get; set; }
        public string strangeTypeName { get; set; }
        public string y_viewUrl { get; set; }
        public string y_applyNotice { get; set; }
        public string studentName { get; set; }
        public string y_stuNum { get; set; }
        public string y_examNum { get; set; }
        public int y_sex { get; set; }
        public int y_inYear { get; set; }
        public string y_cardId { get; set; }
        public int y_majorId { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public int y_stuStateId { get; set; }
        public Nullable<int> y_politicsId { get; set; }
        public Nullable<int> y_nationId { get; set; }
        public string y_img { get; set; }
        public string y_tel { get; set; }
        public string y_mail { get; set; }
        public string y_address { get; set; }
        public string y_registerState { get; set; }
        public int y_isChangePlan { get; set; }
        public Nullable<int> y_changePlanId { get; set; }
        public string y_loginName { get; set; }
        public string y_password { get; set; }
        public Nullable<int> y_stuStrange { get; set; }
        public int y_isdel { get; set; }
        public string schoolCode { get; set; }
        public string schoolName { get; set; }
        public string stuStateName { get; set; }
        public string y_stuStateCode { get; set; }
        public string nationName { get; set; }
        public string politicsName { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string majorName { get; set; }
        public string majorCode { get; set; }
        public Nullable<int> y_stuYear { get; set; }
        public string stuTypeName { get; set; }
        public string y_stuTypeCode { get; set; }
        public string eduTypeName { get; set; }
        public string y_eduTypeCode { get; set; }
        public string majorLibraryName { get; set; }
        public string majorLibraryCode { get; set; }
        public string y_contentAName { get; set; }
        public string y_contentBName { get; set; }
        public Nullable<int> y_straisdel { get; set; }
        public string y_contentF { get; set; }
        public string y_contentH { get; set; }
        public string y_contentG { get; set; }
        public string y_contentI { get; set; }
        public string y_contentJ { get; set; }
        public System.DateTime y_birthday { get; set; }
        public string y_nameabbreviation { get; set; }
        public string y_url { get; set; }
    }
}
