//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SubFeeTotal
    {
        public Nullable<int> totalStuCount { get; set; }
        public Nullable<int> noUpStuCount { get; set; }
        public Nullable<int> hasUpStuCount { get; set; }
        public Nullable<int> totalFee { get; set; }
        public Nullable<int> totalUpFee { get; set; }
        public Nullable<int> totalFeeChae { get; set; }
        public Nullable<int> totalNeedUpFee { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public int y_inYear { get; set; }
        public int y_feeYear { get; set; }
        public string schoolName { get; set; }
    }
}
