//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_StrangeReportTotal
    {
        public Nullable<int> totalStuCount { get; set; }
        public string approvalstatus { get; set; }
        public int y_approvalStatus { get; set; }
        public int y_strangeType { get; set; }
        public string strangeTypeName { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public int y_inYear { get; set; }
        public string schoolName { get; set; }
        public string y_nameabbreviation { get; set; }
    }
}
