//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_StuInfo
    {
        public int id { get; set; }
        public string y_name { get; set; }
        public string y_stuNum { get; set; }
        public string y_examNum { get; set; }
        public int y_sex { get; set; }
        public int y_inYear { get; set; }
        public string y_cardId { get; set; }
        public int y_majorId { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public int y_stuStateId { get; set; }
        public Nullable<int> y_politicsId { get; set; }
        public Nullable<int> y_nationId { get; set; }
        public string y_img { get; set; }
        public string y_tel { get; set; }
        public string y_mail { get; set; }
        public string y_address { get; set; }
        public string y_registerState { get; set; }
        public int y_isChangePlan { get; set; }
        public Nullable<int> y_changePlanId { get; set; }
        public string y_loginName { get; set; }
        public string y_password { get; set; }
        public Nullable<int> y_stuStrange { get; set; }
        public int y_isdel { get; set; }
        public string y_classNum { get; set; }
        public string schoolCode { get; set; }
        public string schoolName { get; set; }
        public string stuStateName { get; set; }
        public string y_stuStateCode { get; set; }
        public string nationName { get; set; }
        public string politicsName { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string majorName { get; set; }
        public string majorCode { get; set; }
        public Nullable<int> y_stuYear { get; set; }
        public string stuTypeName { get; set; }
        public string y_stuTypeCode { get; set; }
        public string eduTypeName { get; set; }
        public string y_eduTypeCode { get; set; }
        public string majorLibraryName { get; set; }
        public string majorLibraryCode { get; set; }
        public string y_StandardCode { get; set; }
        public string subSchoolCode { get; set; }
        public System.DateTime y_birthday { get; set; }
        public Nullable<int> y_isMoneyOk { get; set; }
        public Nullable<int> y_applyOK { get; set; }
        public Nullable<int> y_ischeck { get; set; }
        public Nullable<int> y_degreeOK { get; set; }
        public Nullable<System.DateTime> y_graduationdata { get; set; }
        public string y_graduationschool { get; set; }
        public string y_registrationNum { get; set; }
        public string y_postalcode { get; set; }
        public Nullable<int> y_foreignLanguageId { get; set; }
        public Nullable<int> y_recruitTypeId { get; set; }
        public Nullable<int> y_professionTypeId { get; set; }
        public Nullable<int> y_cultureExtentId { get; set; }
        public Nullable<int> y_examFeatureId { get; set; }
        public string y_foreignLanguageCode { get; set; }
        public string y_foreignLanguageName { get; set; }
        public string y_cultureExtentCode { get; set; }
        public string y_cultureExtentName { get; set; }
        public string y_professionTypeCode { get; set; }
        public string y_professionTypeName { get; set; }
        public string y_recruitTypeCode { get; set; }
        public string y_recruitTypeName { get; set; }
        public string y_ZJTD { get; set; }
        public string y_examFeatureCode { get; set; }
        public string y_examFeatureName { get; set; }
        public string y_TZF { get; set; }
        public string y_nameabbreviation { get; set; }
        public string y_formername { get; set; }
        public Nullable<int> y_studentType { get; set; }
        public Nullable<int> y_realYear { get; set; }
        public Nullable<bool> y_isgraduate { get; set; }
        public Nullable<int> y_isPay { get; set; }
        public string y_graduateNumber { get; set; }
        public Nullable<bool> isCheckForSchool { get; set; }
        public Nullable<bool> y_bachelordegree { get; set; }
        public Nullable<bool> isbachelorForcheck { get; set; }
        public Nullable<bool> y_bachelordegreeCheck { get; set; }
        public Nullable<int> y_examScore { get; set; }
        public string y_origin { get; set; }
        public string y_degreeNum { get; set; }
        public Nullable<int> y_scoreOk { get; set; }
        public string subaddress { get; set; }
        public string subcontact { get; set; }
        public string subtel { get; set; }
        public Nullable<int> y_IsWorking { get; set; }
        public string y_cardType { get; set; }
        public string y_parentCard1 { get; set; }
        public string y_parentCard2 { get; set; }
        public string y_parentName1 { get; set; }
        public string y_parentName2 { get; set; }
        public string y_parentCardType1 { get; set; }
        public string y_parentCardType2 { get; set; }
        public Nullable<int> y_ImgIsok { get; set; }
        public string y_ApprovalNumber { get; set; }

    }
}
