//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Score
    {
        public int id { get; set; }
        public int y_stuId { get; set; }
        public string y_stuNum { get; set; }
        public string y_cardId { get; set; }
        public int y_term { get; set; }
        public decimal y_normalScore { get; set; }
        public decimal y_termScore { get; set; }
        public decimal y_totalScore { get; set; }
        public int y_courseId { get; set; }
        public string y_courseCode { get; set; }
        public string y_courseName { get; set; }
        public string y_stuName { get; set; }
        public string y_examNum { get; set; }
        public Nullable<int> y_sex { get; set; }
        public Nullable<int> y_inYear { get; set; }
        public Nullable<int> y_majorId { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public Nullable<int> y_stuStateId { get; set; }
        public Nullable<int> y_politicsId { get; set; }
        public Nullable<int> y_nationId { get; set; }
        public string y_img { get; set; }
        public string y_tel { get; set; }
        public string y_mail { get; set; }
        public string y_address { get; set; }
        public string y_registerState { get; set; }
        public Nullable<int> y_isChangePlan { get; set; }
        public Nullable<int> y_changePlanId { get; set; }
        public string y_loginName { get; set; }
        public string y_password { get; set; }
        public Nullable<int> y_stuStrange { get; set; }
        public Nullable<int> y_isdel { get; set; }
        public string schoolCode { get; set; }
        public string schoolName { get; set; }
        public string stuStateName { get; set; }
        public string y_stuStateCode { get; set; }
        public string nationName { get; set; }
        public string politicsName { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string majorName { get; set; }
        public string majorCode { get; set; }
        public Nullable<int> y_stuYear { get; set; }
        public string stuTypeName { get; set; }
        public string y_stuTypeCode { get; set; }
        public string eduTypeName { get; set; }
        public string y_eduTypeCode { get; set; }
        public string majorLibraryName { get; set; }
        public string majorLibraryCode { get; set; }
        public Nullable<decimal> y_workScore { get; set; }
        public int y_type { get; set; }
    }
}
