//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TeachPlanDes
    {
        public int id { get; set; }
        public int y_teaPlanId { get; set; }
        public int y_courseId { get; set; }
        public int y_courseTypeId { get; set; }
        public int y_stuTime { get; set; }
        public decimal y_score { get; set; }
        public string y_code { get; set; }
        public string courseName { get; set; }
        public string courseTypeName { get; set; }
        public int y_courseTypeCode { get; set; }
        public string y_teaPlanName { get; set; }
        public int y_term { get; set; }
    }
}
