//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_EduType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YD_Edu_EduType()
        {
            this.YD_Fee_AllBili = new HashSet<YD_Fee_AllBili>();
            this.YD_Fee_SubFeeSys = new HashSet<YD_Fee_SubFeeSys>();
            this.YD_Edu_Major = new HashSet<YD_Edu_Major>();
        }
    
        public int id { get; set; }
        public string y_name { get; set; }
        public string y_eduTypeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Fee_AllBili> YD_Fee_AllBili { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Fee_SubFeeSys> YD_Fee_SubFeeSys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Edu_Major> YD_Edu_Major { get; set; }
    }
}
