//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_CourseCorrespondence
    {
        public int id { get; set; }
        public int y_inyear { get; set; }
        public string y_qingshuMajorlib { get; set; }
        public string y_qingshuEdutype { get; set; }
        public string y_qingshuCourse { get; set; }
        public int y_qingshuTerm { get; set; }
        public int y_MajorID { get; set; }
        public int y_CourseID { get; set; }
        public int y_Term { get; set; }
    }
}
