//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_TeachPlanTemp
    {
        public int id { get; set; }
        public Nullable<int> y_year { get; set; }
        public Nullable<int> y_majorId { get; set; }
        public string y_major { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public string y_majorLib { get; set; }
        public string y_majorNameMatch { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public string y_stuTypeName { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string y_eduTypeName { get; set; }
        public Nullable<int> y_term { get; set; }
        public Nullable<int> y_courseId { get; set; }
        public string y_courseName { get; set; }
        public string y_courseNameMatch { get; set; }
        public Nullable<int> y_courseTypeId { get; set; }
        public string y_courseType { get; set; }
        public Nullable<int> y_stuTime { get; set; }
        public Nullable<int> y_teachPlanType { get; set; }
        public Nullable<decimal> y_score { get; set; }
        public int y_isok { get; set; }
    }
}
