//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_TeachplanDes
    {
        public int id { get; set; }
        public int y_teaPlanId { get; set; }
        public int y_courseId { get; set; }
        public int y_courseTypeId { get; set; }
        public int y_stuTime { get; set; }
        public decimal y_score { get; set; }
        public Nullable<int> y_faceTime1 { get; set; }
        public Nullable<int> y_faceTime2 { get; set; }
        public Nullable<int> y_task { get; set; }
    
        public virtual YD_Edu_Course YD_Edu_Course { get; set; }
        public virtual YD_Edu_CourseType YD_Edu_CourseType { get; set; }
        public virtual YD_Edu_TeachPlan YD_Edu_TeachPlan { get; set; }
    }
}
