//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_MajorTeachPlan
    {
        public int id { get; set; }
        public int y_year { get; set; }
        public int y_majorId { get; set; }
        public int y_teachPlanId { get; set; }
        public int y_teaPlanType { get; set; }
    
        public virtual YD_Edu_Major YD_Edu_Major { get; set; }
        public virtual YD_Edu_TeachPlan YD_Edu_TeachPlan { get; set; }
    }
}
