//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_SmallPower
    {
        public int id { get; set; }
        public int y_year { get; set; }
        public int y_adminId { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public Nullable<int> y_majorId { get; set; }
        public Nullable<int> y_courseType { get; set; }
        public Nullable<int> y_courseId { get; set; }
        public Nullable<int> y_scorelimit { get; set; }
        public System.DateTime y_endTime { get; set; }
        public System.DateTime y_createTime { get; set; }
        public Nullable<int> y_term { get; set; }
    
        public virtual YD_Edu_Course YD_Edu_Course { get; set; }
        public virtual YD_Edu_Major YD_Edu_Major { get; set; }
        public virtual YD_Sys_SubSchool YD_Sys_SubSchool { get; set; }
    }
}
