//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_Major
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YD_Edu_Major()
        {
            this.YD_Sts_StuInfo_copy1 = new HashSet<YD_Sts_StuInfo_copy1>();
            this.YD_Fee_SubFeeSys = new HashSet<YD_Fee_SubFeeSys>();
            this.YD_Edu_MajorTeachPlan = new HashSet<YD_Edu_MajorTeachPlan>();
            this.YD_Edu_SmallPower = new HashSet<YD_Edu_SmallPower>();
            this.YD_Sts_StuInfo = new HashSet<YD_Sts_StuInfo>();
            this.YD_TeaPlan_Class = new HashSet<YD_TeaPlan_Class>();
            this.YD_TeaPlan_Templet = new HashSet<YD_TeaPlan_Templet>();
        }
    
        public int id { get; set; }
        public int y_majorLibId { get; set; }
        public int y_stuTypeId { get; set; }
        public int y_eduTypeId { get; set; }
        public string y_name { get; set; }
        public Nullable<int> y_needFee { get; set; }
        public string y_code { get; set; }
        public int y_stuYear { get; set; }
        public string y_majortype { get; set; }
        public string y_GridType { get; set; }
        public string y_StandardCode { get; set; }
    
        public virtual YD_Edu_EduType YD_Edu_EduType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo_copy1> YD_Sts_StuInfo_copy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Fee_SubFeeSys> YD_Fee_SubFeeSys { get; set; }
        public virtual YD_Edu_MajorLibrary YD_Edu_MajorLibrary { get; set; }
        public virtual YD_Edu_StuType YD_Edu_StuType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Edu_MajorTeachPlan> YD_Edu_MajorTeachPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Edu_SmallPower> YD_Edu_SmallPower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo> YD_Sts_StuInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_TeaPlan_Class> YD_TeaPlan_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_TeaPlan_Templet> YD_TeaPlan_Templet { get; set; }
    }
}
