//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Edu_ScoreTemp
    {
        public int id { get; set; }
        public Nullable<int> y_stuId { get; set; }
        public string y_stuNum { get; set; }
        public string y_examNum { get; set; }
        public Nullable<int> y_term { get; set; }
        public Nullable<int> y_courseId { get; set; }
        public string y_course { get; set; }
        public Nullable<decimal> y_normalScore { get; set; }
        public Nullable<decimal> y_termScore { get; set; }
        public Nullable<decimal> y_workScore { get; set; }
        public Nullable<decimal> y_totalScore { get; set; }
        public string y_stuName { get; set; }
        public int y_isOk { get; set; }
    }
}
