//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Fee_SubFeeSys
    {
        public int id { get; set; }
        public int y_subSchoolId { get; set; }
        public Nullable<int> y_inYear { get; set; }
        public Nullable<int> y_feeYear { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public int y_eduTypeId { get; set; }
        public int y_StuFee { get; set; }
        public Nullable<int> y_bookFee { get; set; }
        public Nullable<int> y_majorid { get; set; }
    
        public virtual YD_Edu_EduType YD_Edu_EduType { get; set; }
        public virtual YD_Edu_Major YD_Edu_Major { get; set; }
        public virtual YD_Sys_SubSchool YD_Sys_SubSchool { get; set; }
    }
}
