//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Fee_StuFeeTb
    {
        public int id { get; set; }
        public int y_stuId { get; set; }
        public int y_feeYear { get; set; }
        public int y_isUp { get; set; }
        public int y_isCheckFee { get; set; }
        public int y_needFee { get; set; }
        public int y_needUpFee { get; set; }
        public Nullable<int> y_planconductOK { get; set; }
        public string y_NoplanconductReason { get; set; }
        public Nullable<int> y_invoiceOK { get; set; }
        public Nullable<int> y_invoiceMoney { get; set; }
        public Nullable<int> y_invoiceUp { get; set; }
        public Nullable<int> y_invoiceCheck { get; set; }
        public Nullable<System.DateTime> y_createtime { get; set; }
        public int y_registerYear { get; set; }
    
        public virtual YD_Sts_StuInfo YD_Sts_StuInfo { get; set; }
    }
}
