//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Fee_StuInvoicee
    {
        public int id { get; set; }
        public int y_subSchoolId { get; set; }
        public string schoolCode { get; set; }
        public string schoolName { get; set; }
        public int totalcount { get; set; }
        public decimal needtotal { get; set; }
        public string y_stuid { get; set; }
        public System.DateTime y_time { get; set; }
        public int y_check { get; set; }
        public Nullable<int> y_feeyear { get; set; }
        public Nullable<int> y_inyear { get; set; }
    }
}
