//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sts_StuInfoTemp
    {
        public int id { get; set; }
        public string y_name { get; set; }
        public Nullable<int> y_sex { get; set; }
        public string y_sexName { get; set; }
        public Nullable<int> y_inYear { get; set; }
        public string y_cardId { get; set; }
        public Nullable<int> y_majorId { get; set; }
        public Nullable<int> y_majorLibId { get; set; }
        public string y_majorLibName { get; set; }
        public string y_majorNameMatch { get; set; }
        public Nullable<int> y_subSchoolId { get; set; }
        public string y_subSchoolName { get; set; }
        public string y_subNameMatch { get; set; }
        public Nullable<int> y_stuTypeId { get; set; }
        public string y_stuTypeName { get; set; }
        public Nullable<int> y_eduTypeId { get; set; }
        public string y_eduTypeName { get; set; }
        public string y_stuNum { get; set; }
        public string y_examNum { get; set; }
        public string y_tel { get; set; }
        public string y_address { get; set; }
        public Nullable<int> y_stuStateId { get; set; }
        public string y_stuStateName { get; set; }
        public int y_isOk { get; set; }
        public Nullable<System.DateTime> y_birthday { get; set; }
        public Nullable<int> y_nationId { get; set; }
        public Nullable<int> y_politicsId { get; set; }
        public string y_nationName { get; set; }
        public string y_politicsName { get; set; }
        public Nullable<System.DateTime> y_graduationdata { get; set; }
        public string y_graduationschool { get; set; }
        public string y_registrationNum { get; set; }
        public string y_postalcode { get; set; }
        public Nullable<int> y_foreignLanguageId { get; set; }
        public string y_foreignLanguageName { get; set; }
        public Nullable<int> y_recruitTypeId { get; set; }
        public string y_recruitTypeName { get; set; }
        public Nullable<int> y_professionTypeId { get; set; }
        public string y_professionTypeName { get; set; }
        public Nullable<int> y_cultureExtentId { get; set; }
        public string y_cultureExtentName { get; set; }
        public Nullable<int> y_examFeatureId { get; set; }
        public string y_examFeatureName { get; set; }
    }
}
