//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sts_StuStrange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YD_Sts_StuStrange()
        {
            this.YD_Sts_StuInfo = new HashSet<YD_Sts_StuInfo>();
            this.YD_Sts_StuInfo_copy1 = new HashSet<YD_Sts_StuInfo_copy1>();
        }
    
        public int id { get; set; }
        public int y_strangeType { get; set; }
        public System.DateTime y_applyTime { get; set; }
        public string y_applyReason { get; set; }
        public string y_approvalReason { get; set; }
        public Nullable<System.DateTime> y_approvalTime { get; set; }
        public int y_approvalStatus { get; set; }
        public Nullable<int> y_approvalAdmin { get; set; }
        public int y_applyAdmin { get; set; }
        public string y_contentA { get; set; }
        public string y_contentB { get; set; }
        public string y_contentC { get; set; }
        public string y_contentD { get; set; }
        public string y_contentE { get; set; }
        public int y_isExecutive { get; set; }
        public Nullable<System.DateTime> y_ExecutiveTime { get; set; }
        public int y_stuId { get; set; }
        public Nullable<int> y_isdel { get; set; }
        public string y_contentF { get; set; }
        public string y_contentG { get; set; }
        public string y_contentH { get; set; }
        public string y_contentI { get; set; }
        public string y_contentJ { get; set; }
        public string y_url { get; set; }
    
        public virtual YD_Sts_StrangeType YD_Sts_StrangeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo> YD_Sts_StuInfo { get; set; }
        public virtual YD_Sts_StuInfo YD_Sts_StuInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo_copy1> YD_Sts_StuInfo_copy1 { get; set; }
    }
}
