//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sys_File
    {
        public int id { get; set; }
        public string y_name { get; set; }
        public Nullable<System.DateTime> y_time { get; set; }
        public Nullable<int> y_createduser { get; set; }
        public Nullable<int> y_role { get; set; }
        public string y_createdName { get; set; }
        public string y_path { get; set; }
    }
}
