//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sys_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YD_Sys_Admin()
        {
            this.YD_Sys_AdminCourseLink = new HashSet<YD_Sys_AdminCourseLink>();
            this.YD_Sys_AdminSubLink = new HashSet<YD_Sys_AdminSubLink>();
            this.YD_Sys_DbLog = new HashSet<YD_Sys_DbLog>();
        }
    
        public int id { get; set; }
        public string y_name { get; set; }
        public string y_password { get; set; }
        public int y_roleID { get; set; }
        public System.DateTime y_time { get; set; }
        public string y_realName { get; set; }
        public string y_phone { get; set; }
        public string y_realpassword { get; set; }
        public string y_qinshuName { get; set; }
        public string y_qinshuPwd { get; set; }
    
        public virtual YD_Sys_Role YD_Sys_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sys_AdminCourseLink> YD_Sys_AdminCourseLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sys_AdminSubLink> YD_Sys_AdminSubLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sys_DbLog> YD_Sys_DbLog { get; set; }
    }
}
