//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sts_SubStuTemp
    {
        public int id { get; set; }
        public int y_subSchoolId { get; set; }
        public string y_name { get; set; }
        public string y_examNum { get; set; }
        public string y_cardId { get; set; }
        public string y_cardIdTemp { get; set; }
        public int y_isOk { get; set; }
        public Nullable<int> y_year { get; set; }
    
        public virtual YD_Sys_SubSchool YD_Sys_SubSchool { get; set; }
    }
}
