//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sys_Power
    {
        public int id { get; set; }
        public int y_roleID { get; set; }
        public int y_moduleID { get; set; }
        public int y_menu { get; set; }
        public int y_insert { get; set; }
        public int y_delete { get; set; }
        public int y_update { get; set; }
        public int y_select { get; set; }
        public Nullable<int> y_down { get; set; }
    
        public virtual YD_Sys_Module YD_Sys_Module { get; set; }
        public virtual YD_Sys_Role YD_Sys_Role { get; set; }
    }
}
