//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_Sys_SubSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YD_Sys_SubSchool()
        {
            this.YD_Edu_SmallPower = new HashSet<YD_Edu_SmallPower>();
            this.YD_Fee_SubFeeSys = new HashSet<YD_Fee_SubFeeSys>();
            this.YD_Graduate_Bachelor = new HashSet<YD_Graduate_Bachelor>();
            this.YD_Graduate_StudentApply = new HashSet<YD_Graduate_StudentApply>();
            this.YD_Sts_StuInfo = new HashSet<YD_Sts_StuInfo>();
            this.YD_Sts_StuInfo_copy1 = new HashSet<YD_Sts_StuInfo_copy1>();
            this.YD_Sts_SubSchoolStuInfo = new HashSet<YD_Sts_SubSchoolStuInfo>();
            this.YD_Sts_SubStuTemp = new HashSet<YD_Sts_SubStuTemp>();
            this.YD_TeaPlan_Class = new HashSet<YD_TeaPlan_Class>();
            this.YT_Teacher = new HashSet<YT_Teacher>();
        }
    
        public int id { get; set; }
        public string y_code { get; set; }
        public string y_name { get; set; }
        public string y_nameabbreviation { get; set; }
        public string y_formername { get; set; }
        public Nullable<int> y_schooltype { get; set; }
        public string y_address { get; set; }
        public string y_contact { get; set; }
        public string y_tel { get; set; }
        public string y_cash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Edu_SmallPower> YD_Edu_SmallPower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Fee_SubFeeSys> YD_Fee_SubFeeSys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Graduate_Bachelor> YD_Graduate_Bachelor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Graduate_StudentApply> YD_Graduate_StudentApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo> YD_Sts_StuInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_StuInfo_copy1> YD_Sts_StuInfo_copy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_SubSchoolStuInfo> YD_Sts_SubSchoolStuInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_Sts_SubStuTemp> YD_Sts_SubStuTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YD_TeaPlan_Class> YD_TeaPlan_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YT_Teacher> YT_Teacher { get; set; }
    }
}
