//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_TeaPlan_ExamPlan
    {
        public int id { get; set; }
        public string y_majorName { get; set; }
        public string y_courseName { get; set; }
        public System.DateTime y_time { get; set; }
        public string y_subSchoolName { get; set; }
        public int y_year { get; set; }
        public int y_term { get; set; }
    }
}
