//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_TeaPlan_TempletCourseDes
    {
        public int id { get; set; }
        public int y_templetId { get; set; }
        public int y_course { get; set; }
        public int y_team { get; set; }
        public Nullable<int> y_selfPeriod { get; set; }
        public Nullable<int> y_teaPeriod { get; set; }
        public Nullable<int> y_taskPeriod { get; set; }
        public Nullable<int> y_courseType { get; set; }
        public bool y_isMain { get; set; }
        public Nullable<int> y_selfPeriod2 { get; set; }
        public Nullable<int> y_teaPeriod2 { get; set; }
        public Nullable<bool> y_sampleexam { get; set; }
    
        public virtual YD_Edu_Course YD_Edu_Course { get; set; }
        public virtual YD_TeaPlan_Templet YD_TeaPlan_Templet { get; set; }
    }
}
