//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YT_GraduationRegistration
    {
        public int id { get; set; }
        public string y_name { get; set; }
        public string y_stuNum { get; set; }
        public string y_cardId { get; set; }
        public Nullable<int> y_sex { get; set; }
        public Nullable<int> y_inYear { get; set; }
        public string y_majorId { get; set; }
        public string y_subSchoolId { get; set; }
        public string y_nationId { get; set; }
        public string y_tel { get; set; }
        public Nullable<System.DateTime> y_birthday { get; set; }
        public string y_address { get; set; }
        public string y_mail { get; set; }
    }
}
