//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YT_Mechanism
    {
        public int id { get; set; }
        public Nullable<int> y_code { get; set; }
        public string y_name { get; set; }
        public string y_address { get; set; }
        public string y_tel { get; set; }
        public string y_img { get; set; }
        public Nullable<System.DateTime> y_Createtime { get; set; }
    }
}
